function handleException(errorMessage: string):never{
    throw Error(errorMessage);
    
}
function runInfinity():void {
    
}